### ISSUE TITLE
Generate schematic of complete CPACS buildup, including major branches for quick referencing purposes?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DLR-boeh-da/CPACS#192]
```
Comments: 
Generate schematic of complete CPACS buildup, including major branches for 
quick referencing purposes?

Reply: 
collect some ideas

daniel.boehnke@dlr.de
erwin.moerland@dlr.de
```

Original issue reported on code.google.com by `daniel.b...@googlemail.com` on 25 Jan 2012 at 10:56

**Comment by DLR-boeh-da** [comment]
For those interested: It is still possible to generate the overall diagrams via a package called hyperref that works in Eclipse: http://xmlmodeling.com/hypermodel/ 

The package is quite powerful. However, as CPACS becomes more and more complex, the diagramm seems less helpful. Hence, no diagramm will be distributed
