### ISSUE TITLE
Extend massBreakdown 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DLR-boeh-da/CPACS#404]
```
Further nodes are necessary in the fuselage mass breakdown. 
-mStringers --> mStringer
-mFrames --> mFrame

Extend documentation on the link of tanks and mBreakdown. 

Further nodes are necessary in the payload category
-Proposal will be made by Reinhold
```

Original issue reported on code.google.com by `daniel.b...@googlemail.com` on 12 Dec 2014 at 2:52

**Comment by DLR-boeh-da** [comment]
In CPACS there is a definition for nose, main and skid landingGears. However there is no such equivalent in the massBreakdown. 

As these items exit in the CPACS definition, the massBreakdown should be extended accordingly

**Comment by DLR-boeh-da** [comment]
The massBreakdown should hold *all* instead of *sequence* style listing. After all the order is not relevant.

**Comment by DLR-boeh-da** [comment]
Furthermore, due to the fact that all items are described rather explicit by the element name, we might make the name element optional in the mass description type

**Comment by DLR-boeh-da** [comment]
There is no additional layer under equipped engines --> no additional engines may be placed to the right or left side

**Comment by DLR-boeh-da** [comment]
Wing mass --> Currently, there is no super element that takes into account the mass of the complete wing box. Under component segments there are directly the values for spars, ribs, etc. 

Maybe it makes sense to introduce another layer here.

**Comment by DLR-boeh-da** [comment]
Extend child nodes with massDescription Entities

**Comment by DLR-boeh-da** [comment]
An issue brought up by Gabriel concerning the generation of the massBreakdown. 

Currently, the uID is listed in the massDescription element. However, more detailed infomation is listed beside the massDescription. Hence it is hard to reference the more detailed nodes as the UID is not a part of their xPATH. Hence, it might be more reasonable to lift the UID to the upper node. 

Discuss this at the CPACS Developer meeting

**Comment by DLR-boeh-da** [comment]
Check if there is an upward way to address parallel nodes via XPath
