### ISSUE TITLE
UID for mass vectors in Massbreakdown

### ISSUE THREAD

**Issue by codingpoets** [DLR-boeh-da/cpacs#412]
In order to uniquely identify masses within the massBreakdown all the masses which allow multiple entries of the same name, such as 'mWingStructure' in 

.../massBreakdown/mOEM/mEM/mStructure/mWingsStructure

need to specify a uID.
Thus I recommend to include a mandatory uID attribute to those nodes.

**Comment by DLR-boeh-da** [comment]
Each massDescription item has a UID attribute.  Would that be sufficient?

**Comment by codingpoets** [comment]
So true. How could I miss that... That should be enough!
But the tools will still have to know which component the massDescription with a certain UID belongs to. Since the masses are not always directly related to a component I guess this is a different issue.
Therefore I'll close this issue.
