### ISSUE TITLE
Bug: CHM Documentation seems to be broken

### ISSUE THREAD

**Issue by rainman110** [DLR-boeh-da/CPACS#425]
When openning the CPACS 2.3 documentation (*.chm file), only the index is visible. The actual content is somehow not shown:

![cpacs-doc-error](https://cloud.githubusercontent.com/assets/3213107/11193859/3763be3e-8ca9-11e5-9f05-0e4b65ac560f.png)

**Comment by DLR-boeh-da** [comment]
This is usually due to some obscure safety settings under windows. At least, I can display the file on my computer. Can you try a different viewer like chmviewer? This usually works. 

Please, let me know if that solved the problem.

**Comment by rainman110** [comment]
If I uncheck "always ask before open", then the file can be opened without any error.

![cpacs-doc-error-resolved](https://cloud.githubusercontent.com/assets/3213107/11207865/11280008-8d18-11e5-8b74-602ab533c72f.png)

**Comment by codingpoets** [comment]
Another issue can be if you try to open the documentation from a network drive.
If the solution in the previous comment does not work, try copying the file to a local drive.
